%YAML:1.0

#common parameters
#support: 1 imu 1 cam; 1 imu 2 cam: 2 cam;
imu: 1
num_of_cam: 2

imu_topic: "/imu0"
image0_topic: "/cam0/image_raw"
image1_topic: "/cam1/image_raw"
output_path: "/home/pci/output/"

cam0_calib: "kalibr-left.yaml"   #left_kannala_brandt_2018111100668.yaml
cam1_calib: "kalibr-right.yaml"

image_width: 640  # 640 1280
image_height: 400  # 400 800


# Extrinsic parameter between IMU and Camera.
estimate_extrinsic: 0   # 0  Have an accurate extrinsic parameters. We will trust the following imu^R_cam, imu^T_cam, don't change it.
                        # 1  Have an initial guess about extrinsic parameters. We will optimize around your initial guess.

body_T_cam0: !!opencv-matrix
  rows: 4
  cols: 4
  dt: d

#aft aft 21
  data: [ -9.9983027630576604e-01, 1.0569992243603084e-02,
          -1.5089527703209283e-02, 5.1338312070692567e-02,
          -1.0550301638105166e-02, -9.9994338633531776e-01,
          -1.3839290454534148e-03, -1.1540650269500224e-02,
          -1.5103301549023817e-02, -1.2244950910578604e-03,
          9.9988518885624622e-01, -3.7835977434352977e-02, 0., 0., 0., 1. ]

body_T_cam1: !!opencv-matrix
  rows: 4
  cols: 4
  dt: d

#aft aft 21
  data: [ -9.9996384513131775e-01, 6.7914531921487928e-03,
          5.1170884034613656e-03, -6.6471835596880302e-02,
          -6.7301747201895020e-03, -9.9990655733973322e-01,
          1.1898795621347874e-02, -7.9888871122351709e-03,
          5.1974203626134544e-03, 1.1863926522940755e-02,
          9.9991611351604515e-01, -2.8401644162365392e-02, 0., 0., 0., 1. ]

#Multiple thread support
multiple_thread: 1

#feature traker paprameters
max_cnt: 50           # max feature number in feature tracking
min_dist: 30            # min distance between two features
freq: 10                # frequence (Hz) of publish tracking result. At least 10Hz for good estimation. If set 0, the frequence will be same as raw image
F_threshold: 1.0        # ransac threshold (pixel)
show_track: 1           # publish tracking image as topic
flow_back: 1            # perform forward and backward optical flow to improve feature tracking accuracy

#optimization parameters
max_solver_time: 0.04  # max solver itration time (ms), to guarantee real time
max_num_iterations: 8   # max solver itrations, to guarantee real time
keyframe_parallax: 10.0 # keyframe selection threshold (pixel)

#imu parameters       The more accurate parameters you provide, the better performance
acc_n: 1.7214282890825171e-02 #0.09   #0.009          # accelerometer measurement noise standard deviation. #0.2   0.04
gyr_n: 1.2824006913728701e-03 #0.002  #0.12          # gyroscope measurement noise standard deviation.     #0.05  0.004
acc_w: 3.0211238978328057e-04 #0.0004 #0.00004       # accelerometer bias random work noise standard deviation.  #0.02
gyr_w: 3.1239314016016067e-05 #7.0e-7 #0.00004       # gyroscope bias random work noise standard deviation.     #4.0e-5
g_norm: 9.8019967000000001e+00        # gravity magnitude

#unsynchronization parameters
estimate_td: 0                      # online estimate time offset between camera and imu  bac:0
td: -0.00085               # initial value of time offset. unit: s. readed image clock + td = real image clock (IMU clock)  bac:0  td -0.000915->about -0.00085


#loop closure parameters
load_previous_pose_graph: 1        # load and reuse previous pose graph; load from 'pose_graph_save_path'
pose_graph_save_path: "/home/pci/output/" # save and load path
save_image: 1                   # save image in pose graph for visualization prupose; you can close this function by setting 0
